name: Build workflow (to be used by others)

on:
  workflow_call:
    inputs:
      goos:
        required: true
        type: string
      goarch:
        required: true
        type: string

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: GOOS="${{ inputs.goos }}" GOARCH="${{ inputs.goarch }}" go build -o target/ -v ./...

    - uses: actions/upload-artifact@v3
      with:
        name: build-result-${{ inputs.goos }}-${{ inputs.goarch }}
        path: target/
