name: Release

on:
  release:
    types: [created]

jobs:
  build:
    uses: ./.github/workflows/_build.yml
  release:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build-result
          path: ./build-result
      - name: List files
        run: ls -lR
      - name: Create zip
        run: zip build-result.zip build-result/*
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: build-result.zip
          asset_name: build-result.zip
          asset_content_type: application/octet-stream
